apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "userapi.name" . }}-cm"
  labels:
{{ include "userapi.labels" . | indent 4 }}
data:
  EXPOSE_PORT: {{ .Values.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  PKI_VAULT_SERVICE_HOST: {{ tpl .Values.pkiVaultService.host . | quote }}
  PKI_VAULT_SERVICE_PORT: {{ .Values.pkiVaultService.port | quote }}