apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "userapi.name" . }}-ing"
  annotations:
    {{- range $key, $value := .Values.ingress.extraAnnotations  }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  labels: 
{{ include "userapi.labels" . | indent 4 }}
spec:
  {{- if .Values.ingress.hosts }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /api/configuration
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "userapi.name" $ }}
            port: 
              number: {{ $.Values.service.port }}
  {{- end }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ include "userapi.name" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}
