/*
 * User Authentication API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type UserInList struct {

	Id int64 `json:"id"`

	Username string `json:"username"`

	Email string `json:"email"`

	Password string `json:"password,omitempty"`

	Role string `json:"role,omitempty"`
}
