/*
 * User Authentication API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type ChatRequest struct {

	ConversationId int64 `json:"conversationId"`

	Model string `json:"model"`

	Prompt string `json:"prompt"`

	Stream bool `json:"stream"`
}
